# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 211693a4c2512ec7358a70d761c0d2381d83a1e4bd8173ed78a2e6986aa40479165cf8118dccea4e7b0ec14e6a46cf979b2d167f738cd00d7cfd752ea6121af4

test:
  secret_key_base: 3dfc908916ab0c9d7ec52aa5912763f00208fa071aa1927da713e24ed946dc3a769c612509cf94457c003c46902e929ba7e6fd230ba379b5d3ea3db23e14790f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
